### ISSUE TITLE
You run this terminal in sh mode.

### ISSUE THREAD

**Issue by Franz611328** [Magisk-Modules-Repo/energizedprotection#10]
This message shows up in terminal at below , and  i don't know why 

:/ # su                                            
:/ # energized                                     
                                                   
                                                   
You run this terminal in sh mode.                  
                                                   
=> You must run in sh mode.                        
- Energized is only compatible with sh.

**Comment by Franz611328** [comment]
fixed

**Comment by xerta555** [comment]
> fixed

Indeed, it has been fixed with the last BETA, also the last BETA works for you?
