### ISSUE TITLE
CLI Flags

### ISSUE THREAD

**Issue by zQueal** [Magisk-Modules-Repo/energizedprotection#13]
I really hate watching all of the credits that take almost a full minute to initialize the application just to update definitions.

Accepting CLI flags would give users the ability to do certain tasks with automation and without having to wait. E.g.

    energized --update

can be used to update blocking definitions in unison with [init.d](https://github.com/Magisk-Modules-Repo/InitdInjector) on device boot up or every `x` hours, etc.

**Comment by xerta555** [comment]
> Accepting CLI flags would give users the ability to do certain tasks with automation and without having to wait. E.g.

Hi, sorry for the long delay.
Concerning CLI flags implementation, I don't think it represents a considerable difficulty, I think it's possible quite simply, I'll talk to Ador about it.

**Comment by AvinashReddy3108** [comment]
Wow @xerta555 , it would open up a lot of possibilities for updating and managing Energized hosts in the device, faster too !!

**Comment by xerta555** [comment]
> Wow @xerta555 , it would open up a lot of possibilities for updating and managing Energized hosts in the device, faster too !!

Although I have a lot of work on other modules/scripts/software/personal projects, I will take the time to start this.

It is very difficult for me to give an idea of how long this implementation will take me before I even achieve a first test solution, but the main difficulty is that I will start irrevocably by modifying crucial parts of the script as a whole.
That said, I should in principle have little to write pure code to do to respond to this request.

In addition, given the number of potential Energized users, my different renderings will go through several test phases.

**Comment by AvinashReddy3108** [comment]
v.1.2.5 and above has support for CLI flags.
