### ISSUE TITLE
Not Working With Magisk 20.3

### ISSUE THREAD

**Issue by zQueal** [Magisk-Modules-Repo/energizedprotection#16]
# Magisk Fully Updated and Working

![photo_2020-02-23_18-12-32](https://user-images.githubusercontent.com/239193/75122058-fd544500-5667-11ea-8921-795e1524f131.jpg)

# Energized Loads Fine at First

![photo_2020-02-23_18-12-26](https://user-images.githubusercontent.com/239193/75122068-11984200-5668-11ea-9a82-973082cf51c9.jpg)

# Fails & Hangs

![photo_2020-02-23_18-12-29](https://user-images.githubusercontent.com/239193/75122097-45736780-5668-11ea-979b-5c88ef4d27f2.jpg)

Magisk binary is `com.txQQ345io4oFgPML` which is randomized. Was working fine before, but maybe now it's not?

**Comment by AnyByte** [comment]
![Screenshot_20200228-090802](https://user-images.githubusercontent.com/8061587/75514963-da2fe980-5a09-11ea-9e43-716324cf388d.jpg)
Getting the same error with Energized 4.9 and Magisk ce7cb1ee (20306)

**Comment by WrichikBasu** [comment]
Same here in Samsung Galaxy On7 running Android 6.0.1 with Magisk 20.4. Please look into this issue.

**Comment by zQueal** [comment]
pretty clear this is a `wont fix`. I've since moved on.

**Comment by EfficiencyVI** [comment]
Moved on to what? 🤔

**Comment by zQueal** [comment]
[AdAway](https://f-droid.org/app/org.adaway).

![Screenshot_20200421-071918](https://user-images.githubusercontent.com/239193/79860501-c1f0a100-83a0-11ea-91f0-4bc1ae10e9cc.png)
