### ISSUE TITLE
Energized Protection v1.3.2 not working on my device anymore previous version pluot works fine

### ISSUE THREAD

**Issue by Gamemulatorer** [Magisk-Modules-Repo/energizedprotection#22]
I always get this Update disabled in config but I didn't disabled it on config 😔
![Screenshot_2020-06-20-06-31-24](https://user-images.githubusercontent.com/37603562/85184593-ded32300-b2c2-11ea-8ad5-14dfc160bb09.png)

Can't also apply any pack or quit what should I do any help please 🙏

**Comment by Gamemulatorer** [comment]
Nevermind this I will use other adblock app 😑

**Comment by AvinashReddy3108** [comment]
Try `ep -h` to get the full documentation.
Or `ep -m` for the older module's menu system.

**Comment by Gamemulatorer** [comment]
> Try `ep -h` to get the full documentation.
> Or `ep -m` for the older module's menu system.

Will try that thanks btw :)

**Comment by Gamemulatorer** [comment]
Still the same :(

**Comment by AvinashReddy3108** [comment]
> Still the same :(

Ok, forget about the `[*] Update: disabled in config` part.
Does the menu `ep -m` and other operations not work for you?

**Comment by Gamemulatorer** [comment]
It's working now thanks!

**Comment by Gamemulatorer** [comment]
@AvinashReddy3108 can I ask what's the meaning of "the delimiter must be a single character" I try to add a2zapk.com to whitelist but always error 😕
