### ISSUE TITLE
Does not work with Magisk 21.

### ISSUE THREAD

**Issue by Poincare1** [Magisk-Modules-Repo/energizedprotection#26]
I have installed latest Magisk stable (v21) installed onAndroid 10, however Energized Protection refuses to run.  Output below:

` # ep -m

 >Version: 21.0 - not supported.
 > Exiting...

`
Any hope that a fix for using on Android 10 with Magisk stable will arrive?

**Comment by AvinashReddy3108** [comment]
The update to v1.3.3 of the module should fix this, re-open if necessary.
