### ISSUE TITLE
Wget Error - Connection reset by peer

### ISSUE THREAD

**Issue by JackofSpades707** [Magisk-Modules-Repo/energizedprotection#35]
Wget Connection Reset by peer![Screenshot_20210626-222021.jpg](https://user-images.githubusercontent.com/17239750/123533771-00809a80-d6cd-11eb-856e-da67c41d5376.jpg)

**Comment by JackofSpades707** [comment]
+ '[' -d /sbin/.magisk ']'
+ magisk_sbin=/sbin/.magisk
+ modPath=/sbin/.magisk/modules/energizedprotection/system/bin
+ . /sbin/.magisk/modules/energizedprotection/system/bin/setupFiles.sh
+ >/dev/null
+ 2>&1
+ R='\e[01;91m'
+ >/dev/null
+ 2>&1
+ G='\e[01;92m'
+ >/dev/null
+ 2>&1
+ Y='\e[01;93m'
+ >/dev/null
+ 2>&1
+ W='\e[01;97m'
+ >/dev/null
+ 2>&1
+ N='\e[0m'
+ >/dev/null
+ 2>&1
+ NC='\033[0m'
+ alias 'awk= awk'
+ alias 'date= date'
+ alias 'echo= echo'
+ alias 'cat= cat'
+ alias 'clear= clear'
+ alias 'cp= cp'
+ alias 'cut= cut'
+ alias 'grep= grep'
+ alias 'gunzip= gunzip'
+ alias 'gzip= gzip'
+ alias 'head= head'
+ alias 'ls= ls'
+ alias 'mkdir= mkdir'
+ alias 'mv= mv'
+ alias 'printf= printf'
+ alias 'ps= ps'
+ alias 'pwd= pwd'
+ alias 'reset= reset'
+ alias 'rm= rm'
+ alias 'sed= sed'
+ alias 'sleep= sleep'
+ alias 'sort= sort'
+ alias 'touch= touch'
+ alias 'truncate= truncate'
+ alias 'wget= wget'
+ checkMagisk
+ magisk -c
+ cut -d: -f1
+ printMagiskVersion=23.0
+ magisk -V
+ magiskVersion=23000
+ hosts=/data/adb/modules/hosts/system/etc/hosts
+ busyboxPath=/data/adb/magisk
+ return 1
+ checkBusybox
+ 2>/dev/null
+ ls /data/adb/magisk/system/bin/busybox
+ ls /data/adb/magisk/system/xbin/busybox
+ ls /data/adb/magisk/busybox
+ busybox=/data/adb/magisk/busybox
+ 2>/dev/null
+ ls /system/bin/busybox
+ ls /system/sbin/busybox
+ ls /system/xbin/busybox
+ busyboxAuto=/system/xbin/busybox
+ 2>/dev/null
+ ls /system/bin/gzip
+ busyboxManualGzip=/system/bin/gzip
+ 2>/dev/null
+ ls /system/bin/wget
+ ls /system/sbin/wget
+ ls /system/xbin/wget
+ busyboxManualWget=/system/xbin/wget
+ 2>/dev/null
+ ls /system/bin/awk
+ busyboxManualAwk=/system/bin/awk
+ 2>/dev/null
+ ls /system/bin/sort
+ busyboxManualSort=/system/bin/sort
+ 2>/dev/null
+ ls /system/bin/truncate
+ busyboxManualTruncate=/system/bin/truncate
+ '[' -n /data/adb/magisk/busybox ']'
+ /data/adb/magisk/busybox
+ cut -f 2 -d ' '
+ head -1
+ busyboxName=v1.33.1-Magisk
+ return 1
+ checkSystemlessHosts
+ '[' ! -f /data/adb/modules/hosts/system/etc/hosts ']'
+ checkSystemlessHostsPrint='\e[01;92m ✓ \e[0m\e[01;97mSystemless Hosts is enabled.\e[0m'
+ checkShell
+ ps 22851
+ awk '{print $NF}'
+ tail -1
+ currentShell=sh
+ echo sh
+ grep NAME
+ '[' '' ']'
+ 2>/dev/null
+ echo sh
+ sed 's/\/system\/sbin\///'
+ sed 's/\/system\/bin\///'
+ sed 's/\/system\/xbin\///'
+ sed 's/\/bin\///'
+ currentShell=sh
+ echo -e '\e[01;92m ✓ \e[0m\e[01;97mScript running in sh mode. Great!\e[0m'
+ shellType=$'\E[01;92m \u2713 \E[0m\E[01;97mScript running in sh mode. Great!\E[0m'
+ return 1
+ . /sbin/.magisk/modules/energizedprotection/system/bin/mainMenu.sh
+ alias 'wget=/data/adb/magisk/busybox wget'
+ . /sbin/.magisk/modules/energizedprotection/system/bin/strings.sh
+ echo /system/bin/energized
+ sed 's/\/system\/bin\///'
+ sym=energized
+ alias 'wget=/data/adb/magisk/busybox wget'
+ alias 'awk=/data/adb/magisk/busybox awk'
+ directory=/sdcard/EnergizedProtection
+ '[' ! -d /sdcard/EnergizedProtection ']'
+ config=/sdcard/EnergizedProtection/ep.conf
+ >/dev/null
+ 2>&1
+ BL='\e[01;90m'
+ >/dev/null
+ 2>&1
+ R='\e[01;91m'
+ >/dev/null
+ 2>&1
+ LR='\033[1;31m'
+ >/dev/null
+ 2>&1
+ G='\e[01;92m'
+ >/dev/null
+ 2>&1
+ LG='\033[1;32m'
+ >/dev/null
+ 2>&1
+ Y='\e[01;93m'
+ >/dev/null
+ 2>&1
+ LY='\033[1;33m'
+ >/dev/null
+ 2>&1
+ B='\e[01;94m'
+ >/dev/null
+ 2>&1
+ P='\e[01;95m'
+ >/dev/null
+ 2>&1
+ C='\e[01;96m'
+ >/dev/null
+ 2>&1
+ LC='\033[1;36m'
+ >/dev/null
+ 2>&1
+ W='\e[01;97m'
+ >/dev/null
+ 2>&1
+ LW='\033[1;37m'
+ >/dev/null
+ 2>&1
+ N='\e[0m'
+ >/dev/null
+ 2>&1
+ NC='\033[0m'
+ userAgent='Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0'
+ hostsGZ=/sdcard/EnergizedProtection/hosts.gz
+ versionInfo=/sdcard/EnergizedProtection/cache/version.md
+ versionBackup=/sdcard/EnergizedProtection/cache/version.md.bck
+ configBackup=/sdcard/EnergizedProtection/cache/ep.conf.bck
+ filter=/sdcard/EnergizedProtection/cache/filter
+ filterBackup=/sdcard/EnergizedProtection/cache/filter.bck
+ whitelist=/sdcard/EnergizedProtection/whitelist
+ blacklist=/sdcard/EnergizedProtection/blacklist
+ REDIRECTLIST=/sdcard/EnergizedProtection/redirectlist
+ temp=/sdcard/EnergizedProtection/cache/temp
+ atemp=/sdcard/EnergizedProtection/cache/temp.a
+ btemp=/sdcard/EnergizedProtection/cache/temp.b
+ ctemp=/sdcard/EnergizedProtection/cache/temp.c
+ dtemp=/sdcard/EnergizedProtection/cache/temp.d
+ etemp=/sdcard/EnergizedProtection/cache/temp.e
+ ltemp=/sdcard/EnergizedProtection/cache/ltemp
+ ptemp=/sdcard/EnergizedProtection/cache/ptemp
+ stemp=/sdcard/EnergizedProtection/cache/stemp
+ hostsBackup=/sdcard/EnergizedProtection/hosts-backup.gz
+ 2>/dev/null
+ grep 'Version Code' /sdcard/EnergizedProtection/cache/filter
+ sed 's/! Version Code: //'
+ lastUpdated=''
+ sed s/watchdog.energized.pro//
+ grep -o -m 1 '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\} watchdog.energized.pro' /data/adb/modules/hosts/system/etc/hosts
+ currentIP=''
+ >/dev/null
+ 2>&1
+ version='\e[01;93m1.3.5\e[0m'
+ >/dev/null
+ 2>&1
+ releaseDate='\e[01;92mMay 13, 2021\e[0m'
+ date '+%d.%m.%Y %H:%M:%S'
+ date='26.06.2021 22:31:24'
+ setupFilesMin
+ cleanup
+ rm -f /sdcard/EnergizedProtection/filter
+ checkDirectory
+ '[' ! -d /sdcard/EnergizedProtection ']'
+ '[' ! -d /sdcard/EnergizedProtection/cache ']'
+ '[' ! -f /sdcard/EnergizedProtection/blacklist ']'
+ '[' ! -f /sdcard/EnergizedProtection/whitelist ']'
+ '[' ! -f /sdcard/EnergizedProtection/redirectlist ']'
+ '[' ! -f /sdcard/EnergizedProtection/cache/temp ']'
+ '[' ! -f /sdcard/EnergizedProtection/cache/ptemp ']'
+ '[' ! -f /sdcard/EnergizedProtection/cache/stemp ']'
+ '[' ! -f /sdcard/EnergizedProtection/whitelist ']'
+ return 1
+ checkMagisk
+ magisk -c
+ cut -d: -f1
+ printMagiskVersion=23.0
+ magisk -V
+ magiskVersion=23000
+ hosts=/data/adb/modules/hosts/system/etc/hosts
+ busyboxPath=/data/adb/magisk
+ return 1
+ checkSystemlessHosts
+ '[' ! -f /data/adb/modules/hosts/system/etc/hosts ']'
+ checkSystemlessHostsPrint='\e[01;92m ✓ \e[0m\e[01;97mSystemless Hosts is enabled.\e[0m'
+ checkBusybox
+ 2>/dev/null
+ ls /data/adb/magisk/system/bin/busybox
+ ls /data/adb/magisk/system/xbin/busybox
+ ls /data/adb/magisk/busybox
+ busybox=/data/adb/magisk/busybox
+ 2>/dev/null
+ ls /system/bin/busybox
+ ls /system/sbin/busybox
+ ls /system/xbin/busybox
+ busyboxAuto=/system/xbin/busybox
+ 2>/dev/null
+ ls /system/bin/gzip
+ busyboxManualGzip=/system/bin/gzip
+ 2>/dev/null
+ ls /system/bin/wget
+ ls /system/sbin/wget
+ ls /system/xbin/wget
+ busyboxManualWget=/system/xbin/wget
+ 2>/dev/null
+ ls /system/bin/awk
+ busyboxManualAwk=/system/bin/awk
+ 2>/dev/null
+ ls /system/bin/sort
+ busyboxManualSort=/system/bin/sort
+ 2>/dev/null
+ ls /system/bin/truncate
+ busyboxManualTruncate=/system/bin/truncate
+ '[' -n /data/adb/magisk/busybox ']'
+ cut -f 2 -d ' '
+ /data/adb/magisk/busybox
+ head -1
+ busyboxName=v1.33.1-Magisk
+ return 1
+ checkEP
+ '[' -f /data/adb/modules/hosts/system/etc/hosts ']'
+ grep -q watchdog.energized.pro /data/adb/modules/hosts/system/etc/hosts
+ grep -q /extensions/ /data/adb/modules/hosts/system/etc/hosts
+ eonoff='\e[01;91m[×]\e[0m'
+ energizedCheck='\e[01;91m× \e[0m\e[01;97mEnergized Protection not activated.\e[0m'
+ checkEPPack
+ '[' -f /data/adb/modules/hosts/system/etc/hosts ']'
+ grep -q E84S1C-P /data/adb/modules/hosts/system/etc/hosts
+ grep -q E5P4RK-P /data/adb/modules/hosts/system/etc/hosts
+ grep -q E8LU-P /data/adb/modules/hosts/system/etc/hosts
+ grep -q E8LUG0-P /data/adb/modules/hosts/system/etc/hosts
+ grep -q EP0R9-P /data/adb/modules/hosts/system/etc/hosts
+ grep -q EUL71M473-P /data/adb/modules/hosts/system/etc/hosts
+ grep -q EU91F13D-P /data/adb/modules/hosts/system/etc/hosts
+ grep -q /extensions/ /data/adb/modules/hosts/system/etc/hosts
+ epPack=-
+ autoPack=null
+ checkEPExtensionPack
+ '[' -f /data/adb/modules/hosts/system/etc/hosts ']'
+ grep -q EP0R9-P /data/adb/modules/hosts/system/etc/hosts
+ ePCheck=''
+ grep -q EXR3G1094L-P /data/adb/modules/hosts/system/etc/hosts
+ eRCheck=''
+ grep -q EX7R3M3-P /data/adb/modules/hosts/system/etc/hosts
+ eXCheck=''
+ grep -q EXP0R9-P /data/adb/modules/hosts/system/etc/hosts
+ ePLCheck=''
+ grep -q EX50C14L-P /data/adb/modules/hosts/system/etc/hosts
+ eSCheck=''
+ divider=-------------------------------------------------
+ divider2='================================================='
+ divider3=_________________________________________________
+ downloadPack -p basic
+ echo ''

+ pack=basic
+ epPack='Basic Protection'
+ DIR=/basic/formats/hosts.gz
+ pid=22938
+ spinPID 'Pack: Downloading'
+ spin[0]=-
+ spin[1]='\'
+ spin[2]='|'
+ spin[3]=/
+ autoUpdateHosts /basic/formats/hosts.gz
+ 2>/dev/null
+ cleanupTemp
+ kill -0 22938
+ rm -f /sdcard/EnergizedProtection/cache/version.md /sdcard/EnergizedProtection/cache/temp /sdcard/EnergizedProtection/cache/temp.a /sdcard/EnergizedProtection/cache/temp.b /sdcard/EnergizedProtection/cache/temp.c /sdcard/EnergizedProtection/cache/temp.d /sdcard/EnergizedProtection/cache/temp.e /sdcard/EnergizedProtection/cache/ltemp /sdcard/EnergizedProtection/cache/stemp /sdcard/EnergizedProtection/cache/ptemp
+ echo -ne '\e[01;97m\r['
[+ echo -ne '\e[01;93m-'
-+ echo -ne '\e[01;97m]' '\e[01;97mPack: Downloading'
] Pack: Downloading+ sleep 0.1
+ hostsURL=https://block.energized.pro//basic/formats/hosts.gz
+ /data/adb/magisk/busybox wget --no-check-certificate -q -U 'Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0' -O /sdcard/EnergizedProtection/hosts.gz https://block.energized.pro//basic/formats/hosts.gz
+ echo -ne '\e[01;97m\r['
[+ echo -ne '\e[01;93m\'
\+ echo -ne '\e[01;97m]' '\e[01;97mPack: Downloading'
] Pack: Downloading+ sleep 0.1
wget: error getting response: Connection reset by peer
+ >/data/adb/modules/hosts/system/etc/hosts
+ gzip -d -c /sdcard/EnergizedProtection/hosts.gz
gzip: /sdcard/EnergizedProtection/hosts.gz: No such file or directory
+ echo -ne '\e[01;97m\r['
[+ echo -ne '\e[01;93m|'
|+ echo -ne '\e[01;97m]' '\e[01;97mPack: Downloading'
] Pack: Downloading+ sleep 0.1
+ echo -ne '\e[01;97m\r['
[+ echo -ne '\e[01;93m/'
/+ echo -ne '\e[01;97m]' '\e[01;97mPack: Downloading'
] Pack: Downloading+ sleep 0.1
+ 2>/dev/null
+ kill -0 22938
+ echo -en '\e[01;97m\r[\e[0m\e[01;93m✓\e[0m\e[01;97m] Pack: \e[0m\e[01;93mBasic Protection\n\e[0m'
[✓] Pack: Basic Protection
+ grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\} watchdog.energized.pro' /data/adb/modules/hosts/system/etc/hosts
+ sed 's/ watchdog.energized.pro//'
+ currentIP=''
+ '[' -z '' ']'
+ grep ' watchdog.energized.pro' /data/adb/modules/hosts/system/etc/hosts
+ sed 's/ watchdog.energized.pro//'
+ currentIP=''
+ rm -f /sdcard/EnergizedProtection/hosts.gz
+ echo -e '\e[01;97m[*] No extension applied.\e[0m'
[*] No extension applied.
+ /data/adb/magisk/busybox awk '{print $5}'
+ ls -lah /data/adb/modules/hosts/system/etc/hosts
+ size=0
+ echo -e '\e[01;97m[+] Size: \e[0m\e[01;93m0\e[0m'
[+] Size: 0
+ pid=22959
+ setFilter
+ cleanupTemp
+ /data/adb/magisk/busybox wget --no-check-certificate -q -O /sdcard/EnergizedProtection/cache/version.md https://block.energized.pro/VERSION.md
+ rm -f /sdcard/EnergizedProtection/cache/version.md /sdcard/EnergizedProtection/cache/temp /sdcard/EnergizedProtection/cache/temp.a /sdcard/EnergizedProtection/cache/temp.b /sdcard/EnergizedProtection/cache/temp.c /sdcard/EnergizedProtection/cache/temp.d /sdcard/EnergizedProtection/cache/temp.e /sdcard/EnergizedProtection/cache/ltemp /sdcard/EnergizedProtection/cache/stemp /sdcard/EnergizedProtection/cache/ptemp
+ spinPID 'Filter: Updating'
+ spin[0]=-
+ spin[1]='\'
+ spin[2]='|'
+ spin[3]=/
+ 2>/dev/null
+ kill -0 22959
+ echo -ne '\e[01;97m\r['
[+ echo -ne '\e[01;93m-'
-+ echo -ne '\e[01;97m]' '\e[01;97mFilter: Updating'
] Filter: Updating+ sleep 0.1
wget: error getting response: Connection reset by peer
+ cp /sdcard/EnergizedProtection/cache/version.md /sdcard/EnergizedProtection/cache/version.md.bck
+ echo -ne '\e[01;97m\r['
[+ echo -ne '\e[01;93m\'
\+ echo -ne '\e[01;97m]' '\e[01;97mFilter: Updating'
] Filter: Updating+ sleep 0.1
cp: cannot stat '/sdcard/EnergizedProtection/cache/version.md': No such file or directory
+ >/sdcard/EnergizedProtection/cache/filter
+ 2>/dev/null
+ grep 'Version Code' /sdcard/EnergizedProtection/cache/version.md
+ echo -ne '\e[01;97m\r['
[+ echo -ne '\e[01;93m|'
|+ echo -ne '\e[01;97m]' '\e[01;97mFilter: Updating'
] Filter: Updating+ sleep 0.1                                 + echo -ne '\e[01;97m\r['                                     [+ echo -ne '\e[01;93m/'                                      /+ echo -ne '\e[01;97m]' '\e[01;97mFilter: Updating'
] Filter: Updating+ sleep 0.1
+ 2>/dev/null                                                 + kill -0 22959                                               + echo -en '\e[01;97m\r[\e[0m\e[01;93m✓\e[0m\e[01;97m] Filter: \e[0m\e[01;93mUpdated \n\n\e[0m'                             [✓] Filter: Updated

+ printDonate
+ sleep 0.1
+ echo -e '\e[01;93m-------------------------------------------------\e[0m'
-------------------------------------------------
+ sleep 0.1
+ echo -e '\e[01;93m[+] If you loved our work, consider donating.\e[0m'
[+] If you loved our work, consider donating.
+ sleep 0.1
+ echo -e '\e[01;94m  > PayPal: paypal.me/shadmansaleh\e[0m'
  > PayPal: paypal.me/shadmansaleh
+ echo -e '\e[01;93m  > Support: energized.pro/support\e[0m'
  > Support: energized.pro/support
+ echo -e '\e[01;93m-------------------------------------------------\e[0m'
-------------------------------------------------
+ sleep 0.1
+ sleep 0.1

**Comment by JackofSpades707** [comment]
The issue only exists on my Phone when interacting with the target site.

I've tried using wget from `/system/xbin` and `/sbin/.magisk/busybox/wget`

some other URLs from other sites seem to work just fine with that version of wget. (not heavily tested, but no failures, tested without `-q` flag)
On the flip side, using curl seems to actually download the file, but then throws the same error, instead of wget which throws the error immediately.

**Comment by dhruvkrishnavaid** [comment]
Try to open https://www.energized.pro/ in a browser. There's a 523 error... 
It's related to DNS settings of the origin web server. You can get more details on the page.

**Comment by salustre** [comment]
Can someone fix it please?

**Comment by dhruvkrishnavaid** [comment]
No one in the open-source community can resolve this. 😟 Since it's a server related error, only the people who are server admins can resolve this.

**Comment by salustre** [comment]
And who's the sysadmin of this solution? There must be any, right? So won't the real sysadmin please stand up, please stand up 🙃

**Comment by dhruvkrishnavaid** [comment]
I think it's fixed now because ```ping energized.pro``` works. Also, we can now update and install packs. You can close this issue now.

**Comment by salustre** [comment]
I can also confirm that it works!

**Comment by JackofSpades707** [comment]
> It's not just your phone! Try to open https://www.energized.pro/ in a browser. There's a 523 error... It's related to DNS settings of the origin web server. You can get more details on the page.

Doh! I should have checked that before opening this. Sorry. Closing.
