### ISSUE TITLE
Version not supported

### ISSUE THREAD

**Issue by vaindil** [Magisk-Modules-Repo/energizedprotection#38]
Hello! I'm using Magisk Canary, and as of Magisk 24 the module seems to be broken because it doesn't think it's supported.

This is the error I'm getting:

> \>Version: 32fc34f9 - not supported.
> \> Exiting...

**Comment by BongzLee** [comment]
I am getting almost similar error:

:/ $ su
:/ # energized -m

 >Version: 24.1 - not supported.
 > Exiting...
:/ # ep -h

**Comment by heptaspirit** [comment]
Me too, new version magisk or magisk-alpha has same problem.

> f880b575-alpha - not suppport
>Exiting...

**Comment by covar2077** [comment]
Yes same problem with magisk v24

**Comment by AvinashReddy3108** [comment]
The new commits now support Canary versions and Stable Magisk 24.x
