### ISSUE TITLE
Isssue

### ISSUE THREAD

**Issue by erkin98** [Magisk-Modules-Repo/energizedprotection#6]
Wget badadress

**Comment by xerta555** [comment]
> Wget badadress

My pr will fix this issue:
https://github.com/Magisk-Modules-Repo/energizedprotection/pull/5

**Comment by erkin98** [comment]
Merged or still waiting?

**Comment by xerta555** [comment]
> Merged or still waiting?

Still waiting for an unknow reason.

**Comment by xerta555** [comment]
@erkin98 
Hello, as now i have manualy updated the module for Magisk v19, can u try again please ?

**Comment by AvinashReddy3108** [comment]
Pushed fixed to repo, update from magisk manager.
Closing issue now !!
